import "src/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { useCounter } from "src/hooks/useCounter";
import { useBgColor } from "src/hooks/useBgColor";
import { useInputArray } from "src/hooks/useInputArray";

function MyApp({ Component, pageProps }: AppProps) {
  useBgColor();
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} {...useCounter()} {...useInputArray()} />
    </>
  );
}

export default MyApp;
